#!/usr/bin/env bash
# FlowMind AI - local dev bootstrap
#
# Brings up Docker infra (Postgres control + client-a, Redis, MinIO),
# migrates/seeds DBs, fixes host-local connection URLs, syncs demo client ID,
# then starts API + web (desktop optional).
#
# Usage:
#   ./scripts/dev-up.sh              # full setup + start API & web
#   ./scripts/dev-up.sh --no-start   # setup only (no long-running processes)
#   ./scripts/dev-up.sh --desktop    # also launch Electron desktop
#   ./scripts/dev-up.sh --infra-only # docker services only
#   ./scripts/dev-up.sh --help
#
# Stop later with: ./scripts/dev-down.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# --- defaults / flags ---
START_APPS=1
START_DESKTOP=0
INFRA_ONLY=0
SKIP_INSTALL=0

CONTROL_URL_HOST="postgresql://flowmind:flowmind_dev@localhost:5432/flowmind_control"
CLIENT_URL_HOST="postgresql://client_a:client_a_dev@localhost:5433/client_a_db"
API_PORT="${PORT:-4000}"
WEB_PORT="${WEB_PORT:-3000}"
LOG_DIR="${ROOT}/.dev-logs"
PID_DIR="${ROOT}/.dev-pids"

for arg in "$@"; do
  case "$arg" in
    --no-start) START_APPS=0 ;;
    --desktop) START_DESKTOP=1 ;;
    --infra-only) INFRA_ONLY=1; START_APPS=0 ;;
    --skip-install) SKIP_INSTALL=1 ;;
    -h|--help)
      awk 'NR==1{next} /^#/{sub(/^# ?/,""); print; next} {exit}' "$0"
      exit 0
      ;;
    *)
      echo "Unknown option: $arg (try --help)"
      exit 1
      ;;
  esac
done

log()  { printf '\n\033[1;36m==>\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32mOK\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31mERR\033[0m %s\n' "$*" >&2; exit 1; }

# --- prerequisites ---
log "Checking prerequisites"
command -v node >/dev/null 2>&1 || die "Node.js not found. Install Node >= 20."
command -v npm  >/dev/null 2>&1 || die "npm not found."
command -v docker >/dev/null 2>&1 || die "Docker not found. Install Docker Desktop."

NODE_VER="$(node -v 2>/dev/null || true)"
if ! node -e "process.exit(0)" 2>/dev/null; then
  die "Node is installed but broken (often missing openssl@3). Try: brew install openssl@3"
fi
ok "Node ${NODE_VER}"

if ! docker info >/dev/null 2>&1; then
  die "Docker daemon not running. Start Docker Desktop and re-run."
fi
ok "Docker is running"

# --- install deps ---
if [[ "$SKIP_INSTALL" -eq 0 ]]; then
  if [[ ! -d "$ROOT/node_modules" ]]; then
    log "Installing npm workspaces (first run)"
    npm install
  else
    log "node_modules present - skipping npm install"
  fi
else
  warn "Skipping npm install (--skip-install)"
fi

# --- docker infra ---
log "Starting infrastructure (postgres-control, postgres-client-a, redis, minio)"
docker compose -f infra/docker-compose.yml up -d \
  postgres-control postgres-client-a redis minio minio-init

wait_pg() {
  local container="$1" user="$2" db="$3" label="$4"
  local i=0
  until docker exec "$container" pg_isready -U "$user" -d "$db" >/dev/null 2>&1; do
    i=$((i + 1))
    if [[ $i -gt 60 ]]; then
      die "Timeout waiting for $label ($container)"
    fi
    sleep 1
  done
  ok "$label ready"
}

wait_pg fm-postgres-control flowmind flowmind_control "Control Postgres"
wait_pg fm-postgres-client-a client_a client_a_db "Client-a Postgres"

if [[ "$INFRA_ONLY" -eq 1 ]]; then
  ok "Infra only - done."
  echo "  Control DB: $CONTROL_URL_HOST"
  echo "  Client DB:  $CLIENT_URL_HOST"
  exit 0
fi

# --- api-server .env ---
log "Writing apps/api-server/.env (host-local URLs)"
cat > apps/api-server/.env <<EOF
# Generated by scripts/dev-up.sh - do not commit secrets
DATABASE_URL=${CONTROL_URL_HOST}
CONTROL_DATABASE_URL=${CONTROL_URL_HOST}
JWT_SECRET=dev-super-secret-change-in-real-env
JWT_EXPIRES_IN=7d
ALLOW_DEV_CLIENT_HEADER=true
PORT=${API_PORT}
EOF
ok "apps/api-server/.env"

# --- prisma generate + control migrate ---
log "Prisma generate + control plane migrate"
(
  cd apps/api-server
  export DATABASE_URL="$CONTROL_URL_HOST"
  export CONTROL_DATABASE_URL="$CONTROL_URL_HOST"
  npx prisma generate
  npx prisma migrate deploy
)
ok "Control migrations applied"

# --- seed control ---
log "Seeding control plane (acme client + platform admin)"
(
  export DATABASE_URL="$CONTROL_URL_HOST"
  export CONTROL_DATABASE_URL="$CONTROL_URL_HOST"
  export AI_PROVIDER="${AI_PROVIDER:-stub}"
  npm run seed:control
)
ok "Control plane seeded"

# --- fix client route for host-run API ---
log "Pointing client route at localhost:5433 (host-run API)"
docker exec fm-postgres-control psql -U flowmind -d flowmind_control -v ON_ERROR_STOP=1 \
  -c "UPDATE client_routes SET db_connection_ref = '${CLIENT_URL_HOST}';" >/dev/null
ok "client_routes.db_connection_ref -> localhost:5433"

# --- client data-plane schema ---
log "Applying client data-plane schema (prisma db push)"
(
  cd apps/api-server
  npx prisma db push --url "$CLIENT_URL_HOST"
)
ok "Client DB schema ready"

# --- sync demo auth clientId with seeded acme id ---
log "Syncing demo login clientId with seeded acme client"
ACME_ID="$(docker exec fm-postgres-control psql -U flowmind -d flowmind_control -tA \
  -c "SELECT id FROM clients WHERE slug = 'acme' LIMIT 1;")"
ACME_ID="$(echo "$ACME_ID" | tr -d '[:space:]')"
if [[ -z "$ACME_ID" ]]; then
  die "Could not read acme client id from control DB"
fi
ok "acme client id = $ACME_ID"

AUTH_FILE="apps/api-server/src/modules/auth/auth.service.ts"
python3 - "$AUTH_FILE" "$ACME_ID" <<'PY'
import re, sys
path, acme_id = sys.argv[1], sys.argv[2]
with open(path, "r", encoding="utf-8") as f:
    src = f.read()
new_src, n = re.subn(
    r"(const resolved = \{\s*clientId:\s*')[0-9a-fA-F-]{36}(')",
    r"\g<1>" + acme_id + r"\2",
    src,
    count=1,
    flags=re.DOTALL,
)
if n == 0:
    new_src, n = re.subn(
        r"(clientId:\s*')[0-9a-fA-F-]{36}(')",
        r"\g<1>" + acme_id + r"\2",
        src,
        count=1,
    )
if n == 0:
    print("WARN: could not patch " + path + "; set clientId manually to " + acme_id, file=sys.stderr)
    sys.exit(0)
with open(path, "w", encoding="utf-8") as f:
    f.write(new_src)
print("patched " + path)
PY
ok "auth.service.ts clientId synced"

mkdir -p "$LOG_DIR" "$PID_DIR"

start_bg() {
  local name="$1"
  shift
  local logf="${LOG_DIR}/${name}.log"
  local pidf="${PID_DIR}/${name}.pid"
  if [[ -f "$pidf" ]] && kill -0 "$(cat "$pidf")" 2>/dev/null; then
    warn "${name} already running (pid $(cat "$pidf"))"
    return 0
  fi
  # shellcheck disable=SC2068
  nohup env "$@" >"$logf" 2>&1 &
  echo $! >"$pidf"
  ok "Started ${name} (pid $(cat "$pidf")) -> ${logf}"
}

if [[ "$START_APPS" -eq 1 ]]; then
  log "Building API (tsc -> dist/main.js)"
  (
    cd apps/api-server
    npm run build
  )
  [[ -f apps/api-server/dist/main.js ]] || die "API build failed: dist/main.js missing"
  ok "API build complete"

  log "Starting API on :${API_PORT}"
  start_bg api \
    ALLOW_DEV_CLIENT_HEADER=true \
    CONTROL_DATABASE_URL="$CONTROL_URL_HOST" \
    DATABASE_URL="$CONTROL_URL_HOST" \
    JWT_SECRET=dev-super-secret-change-in-real-env \
    PORT="$API_PORT" \
    bash -c "cd '${ROOT}/apps/api-server' && node dist/main.js"

  log "Waiting for API health"
  ready=0
  for _i in $(seq 1 90); do
    if curl -sf "http://localhost:${API_PORT}/health" >/dev/null 2>&1; then
      ready=1
      break
    fi
    sleep 1
  done
  if [[ "$ready" -eq 1 ]]; then
    ok "API healthy at http://localhost:${API_PORT}/health"
  else
    warn "API did not become healthy in time - check ${LOG_DIR}/api.log"
  fi

  log "Starting Next.js web on :${WEB_PORT}"
  start_bg web \
    bash -c "cd '${ROOT}/apps/web' && npm run dev -- -p ${WEB_PORT}"

  sleep 2
  if curl -sf "http://localhost:${WEB_PORT}/" >/dev/null 2>&1 \
    || curl -sf "http://localhost:${WEB_PORT}/sop-viewer" >/dev/null 2>&1; then
    ok "Web responding at http://localhost:${WEB_PORT}"
  else
    warn "Web may still be compiling - check ${LOG_DIR}/web.log"
  fi

  if [[ "$START_DESKTOP" -eq 1 ]]; then
    log "Building + launching desktop (Electron)"
    (
      cd apps/desktop
      npm run build
    )
    (
      cd apps/desktop
      nohup npx electron . >"${LOG_DIR}/desktop.log" 2>&1 &
      echo $! >"${PID_DIR}/desktop.pid"
    )
    ok "Desktop launched (pid $(cat "${PID_DIR}/desktop.pid" 2>/dev/null || echo '?'))"
  fi
fi

# --- summary (no nested quotes in heredoc) ---
echo
echo "FlowMind local env is ready."
echo
echo "  Control DB:  ${CONTROL_URL_HOST}"
echo "  Client DB:   ${CLIENT_URL_HOST}"
echo "  acme id:     ${ACME_ID:-n/a}"
echo
echo "  API:         http://localhost:${API_PORT}"
echo "  Health:      http://localhost:${API_PORT}/health"
echo "  SOP Viewer:  http://localhost:${WEB_PORT}/sop-viewer"
echo "  MinIO:       http://localhost:9001  (minioadmin / minioadmin)"
echo
echo "  Demo login:  contributor@acme.test / demo123"
echo "               reviewer@acme.test / demo123"
echo "               admin@acme.test / demo123"
echo
echo "  Logs:        ${LOG_DIR}/"
echo "  PIDs:        ${PID_DIR}/"
echo
echo "  Stop apps:   ./scripts/dev-down.sh"
echo "  Stop infra:  ./scripts/dev-down.sh --infra"
echo
echo "  Manual desktop (if not --desktop):"
echo "    cd apps/desktop && npm run build && npx electron ."
echo
echo "  Smoke:"
echo "    curl -s http://localhost:${API_PORT}/health"
echo "    curl -s -X POST http://localhost:${API_PORT}/auth/login \\"
echo "      -H 'Content-Type: application/json' \\"
echo "      -d '{\"email\":\"contributor@acme.test\",\"password\":\"demo123\"}'"
echo
